package gui;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 * Allows a user to enter their master password for further use.
 *
 * @author Jacob Dorman
 */
public class MasterPasswordJDialog extends javax.swing.JDialog {

    private boolean windowExited;

    public MasterPasswordJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        windowExited = true;
    }

    /**
     * Returns the text in the text field if there was proper input, otherwise
     * closes the program if the window was closed.
     *
     * @return the text in the text field
     */
    public String getInput() {
        if (windowExited) {
            System.exit(0);
        }
        return passwordTextField.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordPromptLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gate Keeper");

        passwordPromptLabel.setText("Enter master password:");

        passwordTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MasterPasswordJDialog.this.keyReleased(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(passwordPromptLabel)
                .addGap(18, 18, 18)
                .addComponent(passwordTextField)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(submitButton)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordPromptLabel)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !passwordTextField.getText().equals("")) {
            windowExited = false;
            dispose();
        }
    }//GEN-LAST:event_keyReleased

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        if (!passwordTextField.getText().equals("")) {
            windowExited = false;
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "A master password cannot be empty.", "Invalid master password", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_submitButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel passwordPromptLabel;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
